### ISSUE TITLE
How to put links into docs?

### ISSUE THREAD

**Issue by sirherrbatka** [CommonDoc/codex#16]
Hi, i want to link article from codex. @link(http://lampwww.epfl.ch/papers/idealhashtrees.pdf)(article) does not seem to work. How to add links?

**Comment by svetlyak40wt** [comment]
Right now Scriba supports this format for links:

```
@link[uri="http://lampwww.epfl.ch/papers/idealhashtrees.pdf"](article) 
```

**Comment by sirherrbatka** [comment]
well, thanks.

**Comment by snunez1** [comment]
Can one be closed now?

**Comment by sirherrbatka** [comment]
yes
