### ISSUE TITLE
fixing a small typo in the template css of the last PR I submitted

### ISSUE THREAD

**Issue by frejanordsiek** [CommonDoc/codex#25]
https://github.com/CommonDoc/codex/blob/281f012e2cf49d66ad2e16b7a2c7838d189a44d6/templates/static/nodes.css#L36

I realized I made a typo in my recent PR which got merged (https://github.com/CommonDoc/codex/pull/24). Specifically, I accidentally added a ```]``` near the end of line 36 in templates/static/nodes.css

**Comment by eudoxia0** [comment]
Fixed by https://github.com/CommonDoc/codex/commit/f591d1e12ecc1c926232a437e1a9c1b6cb41ddbb
