### ISSUE TITLE
Any reasons to invent own markup syntax instead of something a lot more easy-to-write and well-known?

### ISSUE THREAD

**Issue by hijarian** [CommonDoc/codex#6]
Just wondering, why Scriba, successor of Scribe, when we already have markup tailored for easy reading and writing - Markdown, AsciiDoc?

**Comment by eudoxia0** [comment]
Codex uses CommonDoc to represent documents. So Codex supports any input and output format that CommonDoc supports, which is currently limited to Scriba and VerTeX for input and HTML for output. This is to make input and output more flexible, e.g., using cl-markdown or 3bmd would only have allowed me to turn Markdown into HTML.

Additionally, Markdown doesn't support the extensibility of Scriba.

I've been discussing a Markup input format with @orthecreedence and the plan is to eventually support more input and output formats.

**Comment by hijarian** [comment]
Oh, so I was just confused by the README, then. Sorry. :) I concluded that Scriba is the _only_ supported markup syntax. Of course, if Codex is based on CommonDoc then it'll accept everything CommonDoc supports. Thank you for clarification.
